#!/usr/bin/python

import sys



lines = sys.stdin.readlines()
lemma = sys.argv[1]
l1 = []
l2 = []
l3 = []
l4 = []
l5 = []
for line in lines:
	num = line.split(':')[0]
	#print(line)
	if 'St_' and '_WaitConnack' in line:
		l1.append(num)
	elif 'St_' and '_Connected' in line:
		l2.append(num)
	elif 'St_' in line:
		l3.append(num)
	elif 'KU( ~skDev )' in line:
		l4.append(num)
	else:
		l5.append(num)

l1.sort(reverse=True)
l2.sort(reverse=True)
l3.sort(reverse=True)


rank = l1+l2+l3+l4+l5
for i in rank:
	print(i)


